---
- name: Deploy Flask Application
  hosts: localhost
  become: yes

  vars_files:
    - vault/secrets.yml

  tasks:
    - name: Deploy a python application into a virtual environment
      include_role:
        name: common
